export enum AuthErrorCode {
	ACCESS_HEADER_MISSING = 'ACCESS_HEADER_MISSING',
	ACCESS_TOKEN_MISSING = 'ACCESS_TOKEN_MISSING',
	ACCESS_TOKEN_INVALID = 'ACCESS_TOKEN_INVALID',
	INVALID_GOOGLE_TOKEN_SIGNATURE = 'INVALID_GOOGLE_TOKEN_SIGNATURE',
	GOOGLE_ID_TOKEN_INVALID = 'GOOGLE_ID_TOKEN_INVALID',
	GOOGLE_EMAIL_MISSING = 'GOOGLE_EMAIL_MISSING',
	GOOGLE_NAME_MISSING = 'GOOGLE_NAME_MISSING'
}
