export const STATISTICS_REPOSITORY = Symbol.for('STATISTICS_REPOSITORY')
export const STATISTICS_SERVICE = Symbol.for('STATISTICS_SERVICE')
export const STATISTICS_CONTROLLER = Symbol.for('STATISTICS_CONTROLLER')
