export const AUTH_SERVICE = Symbol.for('AuthService')
export const AUTH_CONTROLLER = Symbol.for('AuthController')
export const GOOGLE_AUTH_SERVICE = Symbol.for('GoogleAuthService')
export const TOKEN_SERVICE = Symbol.for('TokenService')
export const REFRESH_TOKEN_REPOSITORY = Symbol.for('RefreshTokenRepository')
export const ALLOWED_EMAIL_REPOSITORY = Symbol.for('AllowedEmailRepository')
