export const COLLECTION_REPOSITORY = Symbol('COLLECTION_REPOSITORY')
export const COLLECTION_SERVICE = Symbol('COLLECTION_SERVICE')
export const COLLECTION_CONTROLLER = Symbol('COLLECTION_CONTROLLER')
